# 기존 prefix (C-b) 해제
unbind C-b

# prefix를 C-a로 변경
set -g prefix C-a
bind C-a send-prefix

# 마우스 사용 (선택)
set -g mouse on

# 창/패널 번호 1부터 시작 (선택)
#set -g base-index 1
#setw -g pane-base-index 1

# 색상 지원 (선택)
set -g default-terminal "screen-256color"

# 상태 표시줄의 세션 이름이 잘리지 않도록 왼쪽 영역 확장
set -g status-left-length 40

# 설정 리로드 단축키 (선택, prefix + r)
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# tmux-sessionizer 단축키
bind-key -r f new-window "${HOME}/bin/tmux-sessionizer"
bind-key -n M-f new-window "${HOME}/bin/tmux-sessionizer"
# 0번 윈도우가 없으면 생성하고, 있으면 해당 윈도우로 이동
#bind-key -n M-0 if-shell "tmux list-windows -F '#{window_index}' | grep -qx 0" "select-window -t :0" "new-window -t :0"
bind-key -n M-0 run-shell "${HOME}/bin/tmux-sessionizer --session 0"
bind-key -n M-1 run-shell "${HOME}/bin/tmux-sessionizer --session 1"
bind-key -n M-2 run-shell "${HOME}/bin/tmux-sessionizer --session 2"
bind-key -n M-3 run-shell "${HOME}/bin/tmux-sessionizer --session 3"
bind-key -n M-` if-shell "tmux select-window -t :0 2>/dev/null" "" "new-window"
bind-key -n M-Left previous-window
bind-key -n M-Right next-window
bind-key -n M-n new-window
# Alt+Shift+화살표 좌/우로 세션 이동 (이전/다음 세션)
bind-key -n M-S-Left switch-client -p
bind-key -n M-S-Right switch-client -n
